sudo: required
language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest

after_success:
  - codecov

notifications:
    email: ueslei@outlook.com